"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 21:33:47.821567
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_at'), ['at'], unique=False)

    op.create_table('brand_kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('logo_key', sa.String(length=500), nullable=True),
    sa.Column('logo_position', sa.String(length=20), nullable=False),
    sa.Column('fonts', sa.JSON(), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('caption_theme', sa.String(length=50), nullable=False),
    sa.Column('intro_key', sa.String(length=500), nullable=True),
    sa.Column('outro_key', sa.String(length=500), nullable=True),
    sa.Column('default_layout', sa.String(length=20), nullable=False),
    sa.Column('cta_text', sa.Text(), nullable=True),
    sa.Column('watermark_text', sa.String(length=200), nullable=True),
    sa.Column('safe_zone', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('integration_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('account_label', sa.String(length=200), nullable=False),
    sa.Column('secret_ref', sa.String(length=200), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'account_label')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('worker', sa.String(length=120), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('learnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('code_verifier', sa.String(length=200), nullable=True),
    sa.Column('account_label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('publish_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('handle', sa.String(length=200), nullable=False),
    sa.Column('credential_ref', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_authorization', sa.String(length=30), nullable=False),
    sa.Column('payout_type', sa.String(length=30), nullable=False),
    sa.Column('cpm', sa.Float(), nullable=False),
    sa.Column('min_qualified_views', sa.Integer(), nullable=False),
    sa.Column('max_payout_per_clip', sa.Float(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tracking_window_days', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_platforms', sa.JSON(), nullable=False),
    sa.Column('min_duration', sa.Float(), nullable=False),
    sa.Column('max_duration', sa.Float(), nullable=False),
    sa.Column('required_hashtags', sa.JSON(), nullable=False),
    sa.Column('required_mentions', sa.JSON(), nullable=False),
    sa.Column('required_cta', sa.Text(), nullable=True),
    sa.Column('subtitles_required', sa.Boolean(), nullable=False),
    sa.Column('logo_required', sa.Boolean(), nullable=False),
    sa.Column('allowed_speakers', sa.JSON(), nullable=False),
    sa.Column('forbidden_words', sa.JSON(), nullable=False),
    sa.Column('forbidden_topics', sa.JSON(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('geography', sa.JSON(), nullable=False),
    sa.Column('posting_limits', sa.JSON(), nullable=False),
    sa.Column('human_approval_required', sa.Boolean(), nullable=False),
    sa.Column('extra_rules', sa.JSON(), nullable=False),
    sa.Column('raw_instructions', sa.Text(), nullable=True),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('brand_kit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_kit_id'], ['brand_kits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_slug'), ['slug'], unique=True)

    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_logs_job_id'), ['job_id'], unique=False)

    op.create_table('campaign_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_rules_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('factor', sa.String(length=40), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('min_samples_per_variant', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('origin_url', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('has_audio', sa.Boolean(), nullable=False),
    sa.Column('rights_status', sa.String(length=20), nullable=False),
    sa.Column('rights_basis', sa.String(length=40), nullable=True),
    sa.Column('rights_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'sha256')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_sha256'), ['sha256'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('speakers', sa.JSON(), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('hook_type', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('origin_ref', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('content_score', sa.Float(), nullable=True),
    sa.Column('hook_score', sa.Float(), nullable=True),
    sa.Column('retention_score', sa.Float(), nullable=True),
    sa.Column('emotion_score', sa.Float(), nullable=True),
    sa.Column('context_score', sa.Float(), nullable=True),
    sa.Column('discussion_score', sa.Float(), nullable=True),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('payoff_score', sa.Float(), nullable=True),
    sa.Column('visual_score', sa.Float(), nullable=True),
    sa.Column('campaign_fit_score', sa.Float(), nullable=True),
    sa.Column('performance_prior', sa.Float(), nullable=True),
    sa.Column('diversity_penalty', sa.Float(), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('scorer', sa.String(length=60), nullable=True),
    sa.Column('score_explanations', sa.JSON(), nullable=False),
    sa.Column('compliance_status', sa.String(length=20), nullable=True),
    sa.Column('compliance_reasons', sa.JSON(), nullable=False),
    sa.Column('expected_value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_source_id'), ['source_id'], unique=False)

    op.create_table('source_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'kind', 'version')
    )
    with op.batch_alter_table('source_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_analyses_source_id'), ['source_id'], unique=False)

    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('has_speakers', sa.Boolean(), nullable=False),
    sa.Column('diarizer', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'version')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_source_id'), ['source_id'], unique=False)

    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('platform_metadata', sa.JSON(), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clips_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_source_id'), ['source_id'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sentence_end', sa.Boolean(), nullable=False),
    sa.Column('words', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_segments_transcript_id'), ['transcript_id'], unique=False)

    op.create_table('clip_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('video_key', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True),
    sa.Column('srt_key', sa.String(length=500), nullable=True),
    sa.Column('ass_key', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('layout_used', sa.String(length=30), nullable=True),
    sa.Column('edit_summary', sa.JSON(), nullable=False),
    sa.Column('render_seconds', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clip_id', 'version')
    )
    with op.batch_alter_table('clip_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clip_versions_clip_id'), ['clip_id'], unique=False)

    op.create_table('cost_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_records_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_records_clip_id'), ['clip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_records_source_id'), ['source_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('clip_version_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('experiment_variant', sa.String(length=60), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('actual_payout', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['publish_accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.ForeignKeyConstraint(['clip_version_id'], ['clip_versions.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_clip_id'), ['clip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_scheduled_at'), ['scheduled_at'], unique=False)

    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('avg_watch_seconds', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('followers_gained', sa.Integer(), nullable=True),
    sa.Column('retention', sa.JSON(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_snapshots_post_id'), ['post_id'], unique=False)

    op.create_table('revenue_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revenue_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revenue_records_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revenue_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revenue_records_campaign_id'))

    op.drop_table('revenue_records')
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_post_id'))
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_captured_at'))

    op.drop_table('metric_snapshots')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_posts_clip_id'))
        batch_op.drop_index(batch_op.f('ix_posts_campaign_id'))

    op.drop_table('posts')
    with op.batch_alter_table('cost_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_records_source_id'))
        batch_op.drop_index(batch_op.f('ix_cost_records_clip_id'))
        batch_op.drop_index(batch_op.f('ix_cost_records_campaign_id'))

    op.drop_table('cost_records')
    with op.batch_alter_table('clip_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_versions_clip_id'))

    op.drop_table('clip_versions')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_transcript_id'))

    op.drop_table('transcript_segments')
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clips_source_id'))
        batch_op.drop_index(batch_op.f('ix_clips_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_clips_campaign_id'))

    op.drop_table('clips')
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_source_id'))

    op.drop_table('transcripts')
    with op.batch_alter_table('source_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_analyses_source_id'))

    op.drop_table('source_analyses')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_source_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_campaign_id'))

    op.drop_table('candidates')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_sha256'))
        batch_op.drop_index(batch_op.f('ix_sources_campaign_id'))

    op.drop_table('sources')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_campaign_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('campaign_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_rules_campaign_id'))

    op.drop_table('campaign_rules')
    with op.batch_alter_table('job_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_logs_job_id'))

    op.drop_table('job_logs')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_slug'))

    op.drop_table('campaigns')
    op.drop_table('publish_accounts')
    op.drop_table('oauth_states')
    op.drop_table('learnings')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_after'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))
        batch_op.drop_index(batch_op.f('ix_jobs_dedupe_key'))

    op.drop_table('jobs')
    op.drop_table('integration_credentials')
    op.drop_table('brand_kits')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_at'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
